server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://120.78.134.171:3306/springboot3vue3?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: springboot3vue3
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      max-lifetime: 120000
    #如果需要在一个xml文件中执行多个sql语句 需要在url后面添加：&allowMultiQueries=true
    #  datasource:
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/springboot32vue3?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    #    username: root
    #    password: 020116zh
    #如果需要在一个xml文件中执行多个sql语句 需要在url后面添加：&allowMultiQueries=true
#mybatisplus
#以下为连接池的相关参数配置


#rocketmq配置
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: default
