server:
  port: 8080
spring:
 #阿里云服务器地址
  datasource:
    url: jdbc:mysql://120.78.134.171:3306/springboot32vue3?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: springboot32vue3
    password: 020116
    driver-class-name: com.mysql.cj.jdbc.Driver
    #如果需要在一个xml文件中执行多个sql语句 需要在url后面添加：&allowMultiQueries=true
#mybatisplus
