GET http://localhost:8080/equipment/tempall
###

GET http://localhost:8080/equipment/equipopen
###

GET http://localhost:8080/equipment/openequip?id=5
###

GET http://localhost:8080/equipment/closeequip?id=7
###

GET http://localhost:8080/equipment/test

